// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutoFetchAndroidDBRequest carries arguments for AutoFetchAndroidDB.
 */
export interface AutoFetchAndroidDBRequest {
}

/**
 * AutoFetchAndroidDBResponse is the return envelope for AutoFetchAndroidDB.
 * Files contains one entry per on-device save that was successfully pulled
 * (e.g. both the standard install and the TapTap sandbox install).
 */
export interface AutoFetchAndroidDBResponse {
    "files": PulledDB[] | null;
}

/**
 * CheckWifiUploadRequest carries arguments for CheckWifiUpload.
 */
export interface CheckWifiUploadRequest {
    "token": string;
}

/**
 * CheckWifiUploadResponse is the return envelope for CheckWifiUpload.
 */
export interface CheckWifiUploadResponse {
    "path": string;
}

/**
 * PickAndroidDBManuallyRequest carries arguments for PickAndroidDBManually.
 */
export interface PickAndroidDBManuallyRequest {
}

/**
 * PickAndroidDBManuallyResponse is the return envelope for PickAndroidDBManually.
 * Paths contains one or more user-selected game.db files.
 */
export interface PickAndroidDBManuallyResponse {
    "paths": string[] | null;
}

/**
 * PulledDB is one successfully pulled game.db file.
 */
export interface PulledDB {
    /**
     * on-device path it was pulled from
     */
    "sourcePath": string;

    /**
     * local destination path
     */
    "path": string;
}

/**
 * ReadAndroidSlotsRequest carries arguments for ReadAndroidSlots.
 */
export interface ReadAndroidSlotsRequest {
    "dbPath": string;
}

/**
 * ReadAndroidSlotsResponse is the return envelope for ReadAndroidSlots.
 */
export interface ReadAndroidSlotsResponse {
    "rows": SlotRow[] | null;
}

/**
 * SlotRow mirrors one record of the `slot` table.
 * SourceDB is the local file path the row was read from, so the UI can
 * disambiguate rows coming from multiple game.db files (e.g. when the user
 * has both a standard install and a TapTap install).
 */
export interface SlotRow {
    "id": number;
    "slotIndex": number;
    "userAccount": string;
    "jsonString": string;
    "jsonSize": number;
    "jsonPreview": string;
    "sourceDb": string;
}

/**
 * StartWifiServerRequest carries arguments for StartWifiServer.
 */
export interface StartWifiServerRequest {
}

/**
 * StartWifiServerResponse is the return envelope for StartWifiServer.
 */
export interface StartWifiServerResponse {
    "result": WifiResult | null;
}

/**
 * StopWifiServerRequest carries arguments for StopWifiServer.
 */
export interface StopWifiServerRequest {
}

/**
 * StopWifiServerResponse is the return envelope for StopWifiServer.
 */
export interface StopWifiServerResponse {
}

/**
 * WifiResult holds the connection info for the client.
 */
export interface WifiResult {
    /**
     * Best guess URL for phone access
     */
    "url": string;

    /**
     * localhost URL for local testing
     */
    "localUrl": string;

    /**
     * All available IP-based URLs
     */
    "allUrls": string[] | null;
    "token": string;

    /**
     * Debug info for troubleshooting
     */
    "debugInfo": string;

    /**
     * Listening port
     */
    "port": number;

    /**
     * netsh command to add firewall rule
     */
    "firewallCmd": string;
}
